# Generated by Django 3.1.6 on 2021-10-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='identify',
            new_name='cfname',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='gov_off',
            new_name='city_mun',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='latitude',
            new_name='east_coord',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='longitude',
            new_name='north_coord',
        ),
    ]
