# Generated by Django 3.1.6 on 2021-10-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211002_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Percentage_Staff_not_Covid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Ratio_Ambulance_Patients',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Ratio_Recoverd_Patients',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Ratio_Staff_Patiens',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='kmeans_label',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='total_ipcs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
