# Generated by Django 3.1.6 on 2021-10-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211021_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Ratio_Recoverd_Patients',
            new_name='Ratio_Recovered_Patients',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Ratio_Staff_Patiens',
            new_name='Ratio_Staff_Patients',
        ),
    ]
