# Generated by Django 3.2.8 on 2021-11-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211021_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfname', models.CharField(max_length=100)),
                ('total_covid_patients', models.FloatField(default=0)),
                ('discharged', models.FloatField(default=0)),
                ('conf_died', models.FloatField(default=0)),
            ],
        ),
    ]
