# Generated by Django 3.2.8 on 2021-11-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_data2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data2',
            new_name='Dashboard',
        ),
    ]
