# Generated by Django 4.0 on 2022-03-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_data2_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Percentage_Staff_not_Covid',
            new_name='chances_patient_not_dying',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Ratio_Ambulance_Patients',
            new_name='ratio_patients_per_day_and_total_beds',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Ratio_Recovered_Patients',
            new_name='ratio_staff_not_infected',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Ratio_Staff_Patients',
            new_name='ratio_total_staff_members',
        ),
        migrations.RemoveField(
            model_name='data',
            name='city_mun',
        ),
        migrations.AddField(
            model_name='data',
            name='Image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
