# Generated by Django 4.0 on 2022-04-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_percentage_staff_not_covid_data_chances_patient_not_dying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='total_ambulance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='total_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='total_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='total_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
