# Generated by Django 4.0 on 2022-04-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_data_total_ambulance_data_total_bed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='total_ambulance',
            new_name='ambulance',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='total_bed',
            new_name='total_beds',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='total_patients',
            new_name='total_staff_members',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='total_staff',
            new_name='tpatient_adm',
        ),
    ]
